image: alpine/latest
oauth: pages.sr.ht/PAGES:RW
packages:
  - ruby
  - go
  - hut
  - rsync
secrets:
  - 4c5cebdb-c744-4dfb-a69a-30b9bdfe048c
sources:
  - https://github.com/dngp/dngp.github.io
environment:
  deploy: srht@mgk.ac
  mirror: mirror.mgk.ac
  site: dngp.github.io
tasks:
- install-gems: |
    gem install 'kramdown:2.4.0' 'rss:0.3.0'
- build: |
    cd mgk.ac
    make build
- package: |
    cd mgk.ac/build
    tar -cvz . > ../../site.tar.gz
- upload: |
    sshopts="ssh -o StrictHostKeyChecking=no"
    rsync --rsh="$sshopts" -ruz --delete mgk.ac/build/ $deploy:/var/www/mgk.ac
    hut pages publish -d $site site.tar.gz
    hut pages publish -d $mirror site.tar.gz
